language:
  - Java
  - node_js

before_script:
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  - npm install -g @angular/cli

jdk:
  - oraclejdk11
node_js:
  - node
install: "npm install"